config/routes.rb
Rails.application.routes.draw do
  resources :girls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/girl.rb
class Girl < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: :true
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController
  before_action :set_girl, only: %i[ show edit update destroy ]

  # GET /girls or /girls.json
  def index
    @girls = Girl.all
  end

  # GET /girls/1 or /girls/1.json
  def show
  end

  # GET /girls/new
  def new
    @girl = Girl.new
  end

  # GET /girls/1/edit
  def edit
  end

  # POST /girls or /girls.json
  def create
    @girl = Girl.new(girl_params)

    respond_to do |format|
      if @girl.save
        format.html { redirect_to girl_url(@girl), notice: "Girl was successfully created." }
        format.json { render :show, status: :created, location: @girl }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /girls/1 or /girls/1.json
  def update
    respond_to do |format|
      if @girl.update(girl_params)
        format.html { redirect_to girl_url(@girl), notice: "Girl was successfully updated." }
        format.json { render :show, status: :ok, location: @girl }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /girls/1 or /girls/1.json
  def destroy
    @girl.destroy

    respond_to do |format|
      format.html { redirect_to girls_url, notice: "Girl was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_girl
      @girl = Girl.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def girl_params
      params.require(:girl).permit(:name, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/views/girls/_form.html.erb
<%= form_with(model: girl, local: true) do |form| %>
  <% if girl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(girl.errors.count, "error") %> prohibited this girl from being saved:</h2>

      <ul>
      <% girl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content, class:"form-label" %>
    <%= form.text_area :content, class:"form-control" %>
  </div>

  <div class="form-group">
     <%= form.label :image %>
     <%= form.file_field :image %>
  </div>

  <div class="mb-3 form-check">
    <%= form.submit class:"btn btn-default" %>
  </div>
<% end %>

app/views/girls/edit.html.erb
<h1>Editing Girl</h1>

<%= render 'form', girl: @girl %>

<%= link_to 'Show', @girl %> |
<%= link_to 'Back', girls_path %>

app/views/girls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Girls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @girls.each do |girl| %>
      <tr>
        <td><%= girl.name %></td>
        <td><%= girl.content %></td>
        <td><%= link_to 'Show', girl %></td>
        <td><%= link_to 'Edit', edit_girl_path(girl) %></td>
        <td><%= link_to 'Destroy', girl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Girl', new_girl_path %>

app/views/girls/new.html.erb
<h1>New Girl</h1>

<%= render 'form', girl: @girl %>

<%= link_to 'Back', girls_path %>

app/views/girls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @girl.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @girl.content %>
</p>
<p>
  <strong>image:</strong>
  <%= image_tag(@girl.image.to_s) %>
</p>

<%= link_to 'Edit', edit_girl_path(@girl) %> |
<%= link_to 'Back', girls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>